#!/usr/bin/env bash
# env_setup.sh - prints a block of safe, useful additions for ~/.bashrc on a
# cluster login node.  It prints only; nothing is modified.  Review, then:
#
#   bash env_setup.sh > ~/.bashrc.asc && echo 'source ~/.bashrc.asc' >> ~/.bashrc
#   source ~/.bashrc
#
# Why print instead of edit: an rc file with a typo can lock you out of a
# usable shell (or break every Slurm job, since batch scripts run bash too).
set -euo pipefail

cat <<'RC'
# ---- ASC additions (generated by env_setup.sh; safe to delete) ----------

# 1. Only for interactive shells: aliases and prompts must not run in scp/rsync/batch sessions.
case $- in *i*) ;; *) return ;; esac

# 2. PATH: your own binaries first.  Never `export PATH=...` without $PATH at the end.
[[ -d $HOME/bin ]]        && export PATH="$HOME/bin:$PATH"
[[ -d $HOME/.local/bin ]] && export PATH="$HOME/.local/bin:$PATH"

# 3. Defaults used by many tools
export EDITOR=vim                       # or nano
export LANG=en_US.UTF-8
umask 027                               # new files rw-r-----, dirs rwxr-x---: group can read, others nothing

# 4. History that survives many parallel sessions
export HISTSIZE=50000 HISTFILESIZE=100000
export HISTCONTROL=ignoredups:erasedups
shopt -s histappend                     # append, do not overwrite, on shell exit
shopt -s checkwinsize                   # re-read terminal size after tmux resize

# 5. Prompt: user@host and cwd, so you always know whether you are on the login node
PS1='\u@\h:\w\$ '

# 6. Aliases: shortcuts, never overriding a command with dangerous new semantics
alias ll='ls -lh'
alias la='ls -lah'
alias ..='cd ..'
alias grep='grep --color=auto'
alias sq='squeue -u $USER'                # ASC's own suggestion; --me works too
alias sj='sacct -X --format=JobID,JobName%20,State,Elapsed,MaxRSS,ExitCode'
alias sinfo_short='sinfo -o "%.15P %.5a %.10l %.6D %.6t %N"'
alias parts='sinfo -o %P'                 # just the partition names (ASC docs)

# 7. Functions for things aliases cannot do (arguments)
mkcd() { mkdir -p "$1" && cd "$1"; }
jobinfo() { scontrol show job "$1"; }
# There is no $SCRATCH on the ASC systems: it is $HOME (100 GB, code only) and
# $DATA (10 TB, all research data).  /local and /tmp exist on compute nodes only
# and are wiped when the job ends.
cdd() { cd "${DATA:?DATA is not set - are you on an ASC system?}"; }
quota_asc() {                             # plain `quota` does not work on Spectrum Scale
    local proj=${1:?usage: quota_asc fs7XXXX}
    mmlsquota --block-size auto -j "home_$proj" home
    mmlsquota --block-size auto -j "data_$proj" data
}

# 8. Modules: DO NOT load modules here.  The ASC user documentation calls
#    customising ~/.bashrc "an absolute recommendation to not" do, because it
#    makes jobs fail; module names on ASC carry a Spack hash that changes per
#    architecture, so a line that works on the login node can break every job.
#    Load in the job script, after `module purge`.
# export MODULES_AUTO_HANDLING=1          # the one modules setting that is safe here

# ---- end ASC additions --------------------------------------------------
RC
